export enum TransType {
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
  OPEX = 'OPEX',
  AR_PAYMENT = 'AR_PAYMENT',
  AP_PAYMENT = 'AP_PAYMENT',
  TOOL = 'TOOL',
  INVESTMENT = 'INVESTMENT',
  ALL = 'ALL',
  EQUITY_CHANGE = 'EQUITY_CHANGE'
}